# Dataset Exploration

# Agriculture in Peru: The Producers
    # People by Sector
    # Agricultural Producers

In [1]:
import pandas as pd

# Load the dataset
data = pd.read_csv(r'c:\Users\jcbur\OneDrive - peruvianbusinesscouncil.org\csv files\#9_peru_agriculture\agriculture_employment\employment_sector_gender.csv')

# Display the first few rows
print(data.head())

# Display the summary statistics
print(data.describe())

# Display the column names and types
print(data.info())

   index  Sum of year  region_id    region  sector_id         sector  \
0      1         2011        0.0  Nacional          1    Agricultura
1      2         2011        0.0  Nacional          1    Agricultura
2      3         2011        0.0  Nacional          1    Agricultura
3      4         2011        0.0  Nacional          2  Pesca/Minería
4      5         2011        0.0  Nacional          2  Pesca/Minería

   gender_id   gender  Sum of value_percent
0          0    Total             25.206266
1          2  Mujeres             22.415487
2          1  Hombres             27.409328
3          0    Total              1.883800
4          2  Mujeres              0.293886
             index  Sum of year    region_id   sector_id    gender_id  \
count  7140.000000  7140.000000  7140.000000  7140.00000  7140.000000
mean   3570.500000  2015.988235    10.528824     4.00000     1.000000
std    2061.284794     3.159686     8.201711     2.00014     0.816554
min       1.000000  2011.000000     0.000000     1.00000     0.000000
25%    1785.750000  2013.000000     2.000000     2.00000     0.000000
50%    3570.500000  2016.000000    10.000000     4.00000     1.000000
75%    5355.250000  2019.000000    18.000000     6.00000     2.000000
max    7140.000000  2021.000000    25.000000     7.00000     2.000000

       Sum of value_percent
count           7140.000000
mean              14.285714
std               14.695826
min                0.000000
25%                3.707795
50%                9.386624
75%               20.452249
max               82.954228
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7140 entries, 0 to 7139
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 7140 non-null   int64
 1   Sum of year           7140 non-null   int64
 2   region_id             7140 non-null   float64
 3   region                7140 non-null   object
 4   sector_id             7140 non-null   int64
 5   sector                7140 non-null   object
 6   gender_id             7140 non-null   int64
 7   gender                7140 non-null   object
 8   Sum of value_percent  7140 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 502.2+ KB
None

# Agriculture in Peru: Main Indicators
    # Total Revenue   
    # Agriculture contribution to the National GDP
    # Agriculture Added Value
    # Crops, Land Dedicated to...
    # Harvested Land

In [4]:
import pandas as pd

# Load the dataset
data = pd.read_csv(r'c:\Users\jcbur\OneDrive - peruvianbusinesscouncil.org\csv files\#9_peru_agriculture\agriculture_main_indicators\agriculture_main_indicators_may24.csv')

# Display the first few rows
print(data.head())

# Display the summary statistics
print(data.describe())

# Display the column names and types
print(data.info())

   index  year  gdp_percent  added_value_PEN07
0      1  1994         6.13              11156
1      2  1995         6.06              11842
2      3  1996         6.27              12611
3      4  1997         6.15              13160
4      5  1998         6.18              13177
           index         year  gdp_percent  added_value_PEN07
count  29.000000    29.000000    29.000000          29.000000
mean   15.000000  2008.000000     5.954828       20642.344828
std     8.514693     8.514693     0.546539        6313.033549
min     1.000000  1994.000000     5.180000       11156.000000
25%     8.000000  2001.000000     5.540000       15496.000000
50%    15.000000  2008.000000     5.970000       20600.000000
75%    22.000000  2015.000000     6.270000       25294.000000
max    29.000000  2022.000000     6.970000       32526.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              29 non-null     int64
 1   year               29 non-null     int64
 2   gdp_percent        29 non-null     float64
 3   added_value_PEN07  29 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 1.0 KB
None

# Agriculture in Peru
    # Natural Disasters Affecting Crops

In [6]:
import pandas as pd

# Load the dataset
data = pd.read_csv(r'c:\Users\jcbur\OneDrive - peruvianbusinesscouncil.org\csv files\#9_peru_agriculture\agriculture_disasters\natural_disasters_ha_may24.csv')

# Display the first few rows
print(data.head())

# Display the summary statistics
print(data.describe())

# Display the column names and types
print(data.info())

   index  year  region_id    region  crops_affected_disasters
0      1  2003          0  Nacional                   14056.0
1      2  2003          1  Amazonas                      32.0
2      3  2003          2    Ancash                       0.0
3      4  2003          3  Apurimac                      40.0
4      5  2003          4  Arequipa                     430.0
            index         year   region_id  crops_affected_disasters
count  470.000000   470.000000  470.000000                470.000000
mean   235.500000  2013.244681   12.476596               3020.528432
std    135.821574     5.573097    7.500568              10266.862908
min      1.000000  2003.000000    0.000000                  0.000000
25%    118.250000  2009.000000    6.000000                  0.000000
50%    235.500000  2013.000000   12.000000                 89.000000
75%    352.750000  2018.000000   19.000000               1433.750000
max    470.000000  2022.000000   25.000000              99664.055000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     470 non-null    int64
 1   year                      470 non-null    int64
 2   region_id                 470 non-null    int64
 3   region                    470 non-null    object
 4   crops_affected_disasters  470 non-null    float64
dtypes: float64(1), int64(3), object(1)
memory usage: 18.5+ KB
None

# Agriculture in Peru
    # Bottomline: Socio Economic
    # Bottomline: Access to Credit
    # Bottomline: Access to Training

In [11]:
import pandas as pd

# Load the dataset
data = pd.read_csv(r'C:\Users\jcbur\OneDrive - peruvianbusinesscouncil.org\csv files\#10_peru_producer_profile\final_assignment\producer_profile_gender_gap_2012.csv')

# Display the first few rows
print(data.head())

# Display the summary statistics
print(data.describe())

# Display the column names and types
print(data.info())

   index  region_id    region  gender_id gender  producers_thousands  \
0      1          0  Nacional          1    men             1554.781
1      2          1  Amazonas          1    men               56.037
2      3          2    Ancash          1    men              109.358
3      4          3  Apurimac          1    men               56.581
4      5          4  Arequipa          1    men               37.845

   granted_loans_thousands  illiteracy_percent  postgraduate_percent  \
0                  145.989            8.884209              7.475265
1                    3.880            5.601656              6.085265
2                    4.014           11.872017              6.085265
3                    6.755           13.683038              7.723441
4                    7.400            3.065134             20.068701

   primary_percent  ...    spanish    quechua    aymara   amazonia  \
0        63.799017  ...  63.559241  29.632533  4.165088   2.643138
1        67.500045  ...  81.706729   0.069597  0.010707  18.212966
2        64.436072  ...  34.423636  65.460232  0.025604   0.090528
3        61.842315  ...  11.928032  87.974762  0.035348   0.061858
4        39.275994  ...  71.557669  27.393315  0.885190   0.163826

   requested_loans_percent  trained_thousands  purpose_sales  \
0                  161.192            253.536      61.162552
1                    4.409              8.237      55.446136
2                    4.699              8.482      58.900549
3                    7.179              9.105      44.396182
4                    7.743              9.687      63.853048

   purpose_self_consumption  purpose_self_provision  purpose_animal_food
0                 16.360560                0.856673            21.620215
1                  9.726324                0.824017            34.003523
2                 29.396192                0.224764            11.478495
3                 35.175163                0.520841            19.907814
4                  5.639505                0.613135            29.894312

[5 rows x 28 columns]
           index  region_id  gender_id  producers_thousands  \
count  52.000000  52.000000  52.000000            52.000000
mean   26.500000  12.500000   1.480769            86.353769
std    15.154757   7.573172   0.504505           230.285987
min     1.000000   0.000000   1.000000             0.000000
25%    13.750000   6.000000   1.000000            12.197250
50%    26.500000  12.500000   1.000000            34.942500
75%    39.250000  19.000000   2.000000            73.850000
max    52.000000  25.000000   2.000000          1554.781000

       granted_loans_thousands  illiteracy_percent  postgraduate_percent  \
count                52.000000           52.000000             52.000000
mean                  7.129173           13.844962              8.716383
std                  20.659194           11.056164              5.545550
min                   0.000000            0.000000              0.000000
25%                   0.980250            5.782922              4.876720
50%                   2.449500           11.291077              6.539635
75%                   5.567000           19.527954             12.038730
max                 145.989000           42.032988             22.899829

       primary_percent  secondary_percent  dont_need_loans_percent  ...  \
count        52.000000          52.000000                52.000000  ...
mean         61.280388          25.533360                34.281903  ...
std          17.944400          10.108904                11.848614  ...
min           0.000000           0.000000                 0.000000  ...
25%          52.405804          17.392917                26.845741  ...
50%          63.826886          27.322131                35.116653  ...
75%          74.795634          31.126268                42.664684  ...
max          83.821607          44.375820                56.517740  ...

         spanish    quechua     aymara   amazonia  requested_loans_percent  \
count  52.000000  52.000000  52.000000  52.000000                52.000000
mean   63.808316  25.043571   3.737369   3.564590                 7.892077
std    32.896684  30.589684  10.346938   7.159198                22.805879
min     0.000000   0.000000   0.000000   0.000000                 0.000000
25%    32.476101   0.991719   0.009628   0.090516                 1.098750
50%    72.370147  10.321158   0.033363   0.177575                 2.594500
75%    90.946135  40.122036   0.103189   2.454668                 6.190250
max    99.855009  90.356732  45.927702  31.061189               161.192000

       trained_thousands  purpose_sales  purpose_self_consumption  \
count          52.000000      52.000000                 52.000000
mean           12.270942      57.779368                 17.412211
std            35.695155      21.270894                 14.315088
min             0.000000       0.000000                  0.000000
25%             1.970750      45.938760                  5.072450
50%             4.320000      60.617283                 11.227631
75%             9.021000      72.838262                 27.370327
max           253.536000      99.467693                 48.262558

       purpose_self_provision  purpose_animal_food
count               52.000000            52.000000
mean                 1.096257            19.866010
std                  1.264570            13.446093
min                  0.000000             0.000000
25%                  0.344245            10.860127
50%                  0.668343            16.895329
75%                  1.134137            26.929553
max                  6.865208            52.782028

[8 rows x 26 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     52 non-null     int64
 1   region_id                 52 non-null     int64
 2   region                    52 non-null     object
 3   gender_id                 52 non-null     int64
 4   gender                    52 non-null     object
 5   producers_thousands       52 non-null     float64
 6   granted_loans_thousands   52 non-null     float64
 7   illiteracy_percent        52 non-null     float64
 8   postgraduate_percent      52 non-null     float64
 9   primary_percent           52 non-null     float64
 10  secondary_percent         52 non-null     float64
 11  dont_need_loans_percent   52 non-null     float64
 12  high_interest_percent     52 non-null     float64
 13  no_collateral_percent     52 non-null     float64
 14  other_reasons_percent     52 non-null     float64
 15  red_tape_percent          52 non-null     float64
 16  will_not_get_it_percent   52 non-null     float64
 17  affiliation_percent       52 non-null     float64
 18  spanish                   52 non-null     float64
 19  quechua                   52 non-null     float64
 20  aymara                    52 non-null     float64
 21  amazonia                  52 non-null     float64
 22  requested_loans_percent   52 non-null     float64
 23  trained_thousands         52 non-null     float64
 24  purpose_sales             52 non-null     float64
 25  purpose_self_consumption  52 non-null     float64
 26  purpose_self_provision    52 non-null     float64
 27  purpose_animal_food       52 non-null     float64
dtypes: float64(23), int64(3), object(2)
memory usage: 11.5+ KB
None